// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    $(document).on("click", ".gridly .delete", function(event) {
      var $this, figid, imgUrl, titleVal;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      $this.closest('.brick').remove();
      return $('.gridly').gridly('layout');
    });
    return $('.gridly').gridly();
  });

}).call(this);
